version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
        
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ server port
      - "15672:15672"  # RabbitMQ management console port
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass

  ecommerce.basketservice.api:
    build:
      context: .
      dockerfile: src/Services/Basket/ECommerce.BasketService.API/Dockerfile
    image: ecommerce.basketservice.api
    depends_on:
      - redis
    environment:
      - Redis__Configuration=redis:6379
    ports:
      - "5000:80"

  ecommerce.productservice.api:
    image: ecommerce.productservice.api
    build:
      context: .
      dockerfile: src/Services/ProductService/ECommerce.ProductService.API/Dockerfile
    ports:
      - "5248:80"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/ecommerce
    depends_on:
      - mongo

volumes:
  mongo_data: